# Generated by Django 3.1.7 on 2021-08-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title :')),
                ('description', models.TextField(max_length=500, verbose_name='Description :')),
                ('price', models.IntegerField(null=True, verbose_name='Price :')),
                ('image', models.ImageField(upload_to='image', verbose_name='Pohto :')),
            ],
        ),
    ]
