# Generated by Django 3.1.7 on 2021-08-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='not_1',
            field=models.CharField(max_length=150, null=True, verbose_name='Note 1 :'),
        ),
        migrations.AddField(
            model_name='product',
            name='not_2',
            field=models.CharField(max_length=150, null=True, verbose_name='Note 2 :'),
        ),
        migrations.AddField(
            model_name='product',
            name='not_3',
            field=models.CharField(max_length=150, null=True, verbose_name='Note 3 :'),
        ),
        migrations.AddField(
            model_name='product',
            name='not_4',
            field=models.CharField(max_length=150, null=True, verbose_name='Note 4 :'),
        ),
        migrations.AddField(
            model_name='product',
            name='not_5',
            field=models.CharField(max_length=150, null=True, verbose_name='Note 5 :'),
        ),
    ]
