# Generated by Django 3.1.7 on 2021-08-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210817_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='months',
            field=models.IntegerField(default=1, verbose_name='Months :'),
            preserve_default=False,
        ),
    ]
