# Generated by Django 3.1.7 on 2021-08-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(null=True, verbose_name='Sale Price :'),
        ),
    ]
