# Generated by Django 3.1.7 on 2021-08-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paypal_btn',
            field=models.TextField(default=1, max_length=1000, verbose_name='PayPal Button : '),
            preserve_default=False,
        ),
    ]
