# Generated by Django 3.1.7 on 2021-08-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_paypal_btn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='paypal_btn',
        ),
    ]
