# Generated by Django 3.1.7 on 2021-08-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_paypal_btn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='not_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 1 :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='not_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 2 :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='not_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 3 :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='not_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 4 :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='not_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 5 :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale Price :'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='subtitle :'),
        ),
    ]
