# Generated by Django 3.1.7 on 2021-08-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(max_length=500, null=True, verbose_name='Description :'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(default=1, max_length=250, verbose_name='Title-ar :'),
            preserve_default=False,
        ),
    ]
